### ISSUE TITLE
Closed PRs are still showing on the build dashboard

### ISSUE THREAD

**Issue by witokondoria** [BBVA/mirrorgate#2]
On an unknown version (maybe applies to all of them), every pull request already closed is still showing at the builds.

This behaviour delegates the cleanup duties to the Jenkins' Orphaned Item Strategy functionality.

It might be worth having an additional filtered view, where closed pull requests (generally speaking, any job) kept as disabled at the Jenkins UI are hidden at MirrorGate

**Comment by alfonso-presa** [comment]
Thanks for reporting this issue! We are also having this happening from time to time in our own local installation. We will definitely look at it.

It might be possible to listen to onUpdated event in our own jenkins plugin and report it to MirrorGate as deleted once the job is changed to disabled.

https://github.com/BBVA/mirrorgate-jenkins-builds-collector/blob/develop/src/main/java/com/bbva/arq/devops/ae/mirrorgate/jenkins/plugin/listener/MirrorGateItemListener.java#L48

**Comment by kdaimiel** [comment]
It seems that Jenkins doesn't delete them after a while. It just set them on deactivated mode. We could consider remove all items that are on that state.

**Comment by witokondoria** [comment]
Jenkins will delete items when a full scan is performed and the orphaned item strategy allows each item to be wiped. This applies to bitbucket and github branch-source project types, tho.

**Comment by kdaimiel** [comment]
It is fixed on version v0.0.5 of [BBVA/mirrorgate-jenkins-builds-collector](https://github.com/BBVA/mirrorgate-jenkins-builds-collector/releases/tag/v0.0.5). You can download the last version from [Sonatype OSS](https://oss.sonatype.org/content/repositories/releases/com/bbva/arq/devops/ae/mirrorgate/mirrorgate-publisher/) and update it in your Jenkins instance.

Thanks!
