### ISSUE TITLE
Does this allow me to create new dashboards based on jira filters

### ISSUE THREAD

**Issue by zorianix** [BBVA/mirrorgate#9]
Hi can I create a new custom dashboard based on jira query i specify, ex: reporter=x and project =y and status =open and displays metrics based on jira ticket severity

**Comment by kdaimiel** [comment]
The Jira component of MirrorGate is based on Teams, so It is not prepared to display filters. You can use the team names (as a custom field), board names, project names or project keys as keywords to match jira issues. Perhaps you could create a board with the issues you want to display.
